app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/cases #jdbc:postgresql://${DB_HOST}/${DB_NAME}
    username: postgres #${DB_USER}
    password: postgres #${DB_PASSWORD}
    pool-size: 30
management:
  server:
    port: 8080
  health:
    defaults:
      enabled: true
spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

alerts:
  service:
     host: alerts
     port: 8080